name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install AWS CLI and EB CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install --upgrade pip
        pip3 install awscli --upgrade --user
        pip3 install awsebcli --upgrade --user
        
    - name: Configure AWS credentials
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}
      
    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
    - name: Install dependencies
      working-directory: ./hello-world-app/
      run: npm install
      
    - name: Build Angular application
      working-directory: ./hello-world-app/
      run: ng build --configuration=production
      
    - name: Deploy to Elastic Beanstalk
      run: eb deploy --profile default
